# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cee0f51d1aee093ecd38006b32264e40dd7acd7324dcbefd15bda9b922b4a7b13af5e9865611732da249ef9691601128885f2cba170487dc864017da2822750
  jwt_secret: 'super random key'
  jwt_expiration_hours: 24

test:
  secret_key_base: 20692f16ffbde60ee11dc231d565c4d4fb280b6d7655047307a340e84c67a30654203fe84e5f0d5c0ea7b3bffe8891aec8607c4913ec67a6054fb7abcc1a00bc
  jwt_secret: 'super random key'
  jwt_expiration_hours: 24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jwt_secret: <%= ENV["SECRET_KEY_BASE"] %>
  jwt_expiration_hours: 6
